# Generated by Django 4.1.1 on 2022-10-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0003_auto_20221022_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='pic',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='static/piclocated'),
        ),
        migrations.AlterField(
            model_name='tutor_infor',
            name='VDO',
            field=models.FileField(blank=True, unique=True, upload_to='static/video'),
        ),
        migrations.AlterField(
            model_name='tutor_infor',
            name='performance',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='static/IMG'),
        ),
    ]
