# Generated by Django 4.1.1 on 2022-10-27 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0005_tutor_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DB_teach',
        ),
    ]
